// Embed assets/notification.wav as a base64 constant into the client package.
//
// The browser bundle carries the pre-recorded notification sound inline, so the
// overlay can play the real sound (not the synthesized fallback) with no
// host-side file lookup and no RPC round-trip. The generated `sound.ts` is
// gitignored and regenerated before every client build (see harness-build.mjs).
//
// usage: node scripts/embed-sound.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const wavPath = resolve(repoRoot, "assets", "notification.wav");
const outPath = resolve(repoRoot, "packages", "dsh-human-task-client", "src", "client", "sound.ts");

const bytes = readFileSync(wavPath);
const base64 = bytes.toString("base64");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  [
    "// GENERATED by scripts/embed-sound.mjs — do not edit.",
    "// Source: assets/notification.wav (pre-recorded notification sound).",
    "export const NOTIFICATION_WAV_BASE64 =",
    `  ${JSON.stringify(base64)};`,
    "",
  ].join("\n"),
  "utf8",
);

console.log(
  `[embed-sound] embedded ${wavPath} (${bytes.length} bytes -> ${base64.length} base64 chars) into ${outPath}`,
);
